### ISSUE TITLE
Bidirectional relationships show incorrectly on contact B

### ISSUE THREAD

**Issue by MegaphoneJon** [eileenmcnaughton/org.wikimedia.relationshipblock#11]
To replicate:
* Enable displaying "Spouse of" on Relationship Block.
* Add a "Spouse of" relationship from contact A to contact B.
* Contact A displays contact B as their spouse...but contact B also displays contact A as their spouse.

I'm going to take a first crack at fixing this, I'll let you know how far I get!

**Comment by colemanw** [comment]
Fixed with #13
