### ISSUE TITLE
Ordering of Relationship

### ISSUE THREAD

**Issue by clement888** [eileenmcnaughton/org.wikimedia.relationshipblock#22]
I was wondering is there a way to order the display of the relationships in the Relationship block ?  thanks.

Clement

**Comment by colemanw** [comment]
Currently no.
Arguably the extension should at least put the relationship types in alphabetical order, but it currently doesn't even do that, and they end up in no particular order.

**Comment by mattwire** [comment]
@clement888 Wasn't this fixed by https://github.com/eileenmcnaughton/org.wikimedia.relationshipblock/pull/15 which is in 1.3?
