### ISSUE TITLE
Inline edit too large when contact image

### ISSUE THREAD

**Issue by martinh-pw** [eileenmcnaughton/org.wikimedia.relationshipblock#23]
A bit of an odd corner case happens when a contact has an image. The clickable area for this block (to activate the inline edit form) becomes too large and encompasses the section above (tags, etc). In our case that means that clicking on the drupal userid next to the contactid became unavailable.

This happens because in the condition above civi adds the float-left class to one of the divs. See here:
templates/CRM/Contact/Page/View/Summary.tpl

Not sure if this is the exact right solution, but I was able to fix it by adding class crm-clear to div#crm-relblock-content on line 1 here:
templates/CRM/Relationshipblock/Page/Inline/RelationshipBlock.tpl

Tested on 5.16.3/drupal7 and on dmaster at 5.19.alpha1 (contact id 206).

![image](https://user-images.githubusercontent.com/27358869/64808906-26739400-d566-11e9-9452-85b97a1af38e.png)

**Comment by martinh-pw** [comment]
you betchaaaa

**Comment by mattwire** [comment]
@eileenmcnaughton Can this be closed - looks like it was fixed via #24

**Comment by eileenmcnaughton** [comment]
cool
