### ISSUE TITLE
Syntax error: curly braces with v1.5

### ISSUE THREAD

**Issue by herbdool** [eileenmcnaughton/org.wikimedia.relationshipblock#39]
Getting:

> Deprecated: Array and string offset access syntax with curly braces is deprecated in /app/httpdocs/civicrm_custom/extensions/contrib/relationshipblock/relationshipblock.civix.php on line 246

Looks like it needs to be update with civix. Or cut a new release.

**Comment by colemanw** [comment]
I've updated civix and cut v1.6
